{{ config({ "materialized":'view',

 "alias":'PRODUCT_VIEW',

 "schema": 'GOLD'

})}}

 

WITH view AS(

SELECT

    PRODUCT_ID AS PRODUCT_ID

    ,DBT_VALID_FROM AS VRSN_STRT_DTS

    ,COALESCE(DBT_VALID_TO , '9999-12-31 00:00:00.000') AS VRSN_END_DTS

    ,PRODUCT_NAME AS PRODUCT_NAME

    ,CATEGORY AS CATEGORY

    ,SELLING_PRICE AS SELLING_PRICE

    ,MODEL_NUMBER AS MODEL_NUMBER

    ,ABOUT_PRODUCT AS ABOUT_PRODUCT

    ,PRODUCT_SPECIFICATION AS PRODUCT_SPECIFICATION

    ,TECHNICAL_DETAILS AS TECHNICAL_DETAILS

    ,SHIPPING_WEIGHT AS SHIPPING_WEIGHT

    ,PRODUCT_DIMENSIONS AS PRODUCT_DIMENSIONS

    ,TIME_ZONE

    ,SOURCE_SYS_NAME

    ,INSTNC_ST_NM

    ,PROCESS_ID

    ,PROCESS_NAME

    ,INSERT_DTS

    ,UPDATE_DTS

FROM {{ref('product_snapshot')}}

)

SELECT *

FROM view

 