{{ config({ "materialized":'table',

 "transient":true,

 "alias":'WORK_PRODUCT_TRANSFORM',

 "pre_hook": macros_copy_csv('WORK_PRODUCT_COPY'),

 "schema": 'SILVER'

})}}

 

WITH transform AS(

SELECT 

    PRODUCT_ID AS PRODUCT_ID

    ,PRODUCT_NAME AS PRODUCT_NAME

    ,CATEGORY AS CATEGORY

    ,SELLING_PRICE AS SELLING_PRICE

    ,MODEL_NUMBER AS MODEL_NUMBER

    ,ABOUT_PRODUCT AS ABOUT_PRODUCT

    ,PRODUCT_SPECIFICATION AS PRODUCT_SPECIFICATION

    ,TECHNICAL_DETAILS AS TECHNICAL_DETAILS

    ,SHIPPING_WEIGHT AS SHIPPING_WEIGHT 

    ,PRODUCT_DIMENSIONS AS PRODUCT_DIMENSIONS

    ,'EST' AS TIME_ZONE

    ,'PRODUCT' AS SOURCE_SYS_NAME

    ,'STANDARD' AS INSTNC_ST_NM

    ,CURRENT_SESSION() AS PROCESS_ID

    ,'TRANSFORM_LOAD' AS PROCESS_NAME

    ,INSERT_DTS AS INSERT_DTS

    ,UPDATE_DTS AS UPDATE_DTS

    ,SOURCE_FILE_NAME AS SOURCE_FILE_NAME

    ,SOURCE_FILE_ROW_NUMBER AS SOURCE_FILE_ROW_NUMBER

FROM {{source('source','WORK_PRODUCT_COPY')}}

)

 

SELECT *

FROM transform